name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: good evening

    steps:
    - uses: actions/checkout@v2  
    - name: Run a one-line script
    - run: echo good evening