name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v2  
    - name: Run a one-line script
      run: echo Hello, world!  
        cd C++/helloworld/
        ./build.sh
    - name: test
      run: |
         C++/helloworld/build/test_calc
