name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: label change test1
      run: | 
        pwd
        ls
    - name: label change test2
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: build
      run: |
        cd C++/helloworld/
        ./build.sh
    - name: test
      run: |
         C++/helloworld/build/test_calc  
